### ISSUE TITLE
Undefined variable 

### ISSUE THREAD

**Issue by asvinours** [sous-chefs/grafana#381]
## :ghost: Brief Description

an undefined variable bug was introduced in https://github.com/sous-chefs/grafana/pull/377
https://github.com/sous-chefs/grafana/blob/master/libraries/api_helper.rb#L65
```
>>>> Caused by NameError: undefined local variable or method `port' for cookbook: my-grafana, recipe: ldap :Chef::Recipe
/var/chef/cache/cookbooks/grafana/libraries/api_helper.rb:65:in `do_request'
/var/chef/cache/cookbooks/grafana/libraries/organization_api.rb:140:in `get_orgs_list'
/var/chef/cache/cookbooks/grafana/libraries/organization_api.rb:171:in `get_organization_id'
/var/chef/cache/cookbooks/edt-grafana/recipes/ldap.rb:28:in `block in from_file'
/var/chef/cache/cookbooks/edt-grafana/recipes/ldap.rb:35:in `block (3 levels) in from_file'
```

## :pancakes: Cookbook version

v9.4.0

## :woman_cook:  Chef-Infra Version

v16.x.x

## :tophat: Platform details

CentOS 7

**Comment by ramereth** [comment]
@asvinours thanks for the bug repo. Do you think you could make a PR which fixes this?

**Comment by ramereth** [comment]
@asvinours 9.4.1 has been released with this fix
