### PR TITLE
Bugfix for undefined port variable (#381)

### LINKED ISSUE #381: Undefined variable
## :ghost: Brief Description

an undefined variable bug was introduced in https://github.com/sous-chefs/grafana/pull/377
https://github.com/sous-chefs/grafana/blob/master/libraries/api_helper.rb#L65
```
>>>> Caused by NameError: undefined local variable or method `port' for cookbook: my-grafana, recipe: ldap :Chef::Recipe
/var/chef/cache/cookbooks/grafana/libraries/api_helper.rb:65:in `do_request'
/var/chef/cache/cookbooks/grafana/libraries/organization_api.rb:140:in `get_orgs_list'
/var/chef/cache/cookbooks/grafana/libraries/organization_api.rb:171:in `get_organization_id'
/var/chef/cache/cookbooks/edt-grafana/recipes/ldap.rb:28:in `block in from_file'
/var/chef/cache/cookbooks/edt-grafana/recipes/ldap.rb:35:in `block (3 levels) in from_file'
```

## :pancakes: Cookbook version

v9.4.0

## :woman_cook:  Chef-Infra Version

v16.x.x

## :tophat: Platform details

CentOS 7

### PR DESCRIPTION
**Pull request by axelrtgs**
Fixes https://github.com/sous-chefs/grafana/issues/381

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ramereth — APPROVED** [review]
